BACKGROUND_COLOR = "#a1a09f"
LOG_SIZE = 100

#character
CHARACTER_SIZE = 80
CHARACTER_OFFSET_FROM_LOG = 10
OBSTACLE_SIZE = (190, 48)

OBSTACLE_FREQUENCY = 1000

BACKGROUND_PATH = "assets/background.png"
CHARACTER_PATH = "assets/steve.png"
OBSTACLE_PATH = "assets/tnt-large.png"
ROCKET_PATH = "assets/rocket_fireball.png"

CENTER_TIME_LIMIT = 2000

STAMINA_GAIN = 30
STAMINA_LOSS = 10

ROCKET_HITBOX_TOP_CUT = 75

POWERUOP_FREQUENCY_RANGE = (8000, 20000)